"use client";

import { motion } from "framer-motion";

export function Reframe() {
  return (
    <section className="bg-background border-t border-border">
      <div className="w-full px-6 lg:px-12 py-24 md:py-32">
        <div className="max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <span className="block font-mono text-xs tracking-widest uppercase text-foreground/40 mb-8">
              — The Reframe
            </span>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-sans font-normal leading-[1.15] tracking-tight text-foreground mb-8">
              You have tried the creams. The serums. The elimination diets.{" "}
              <span className="text-foreground/40">
                The dermatologist said it was hormonal. The internet said it was dairy. The cleanser that worked for three weeks stopped working on week four.
              </span>
            </h2>
            <div className="space-y-4 text-base text-foreground/50 leading-relaxed max-w-2xl">
              <p>None of it held because none of it was listening.</p>
              <p>
                Acne, eczema, rosacea, and reactive skin are not random. They are not cosmetic failures. They are biological responses, generated by systems under strain, surfaced through the only organ large enough to show you.
              </p>
              <p className="text-foreground">Your skin is not broken. It is communicating.</p>
              <p className="text-foreground/40">The question is whether you are treating the message or reading it.</p>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
